#pragma once
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416
#define MOVEMENTSPEED 100
#define GRAVITY 200
#define INITIAL_JUMP_FORCE 550
#define JUMP_FORCE_DECREMENT 550
#define MAP_HEIGHT 13
#define MAP_WIDTH 16
#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define SHAKE_DURATION 0.25f
#define INJURED_TIME 2.5f
#define INITIAL_JUMP_FORCE_SMALL 300
#define KOOPA_SPEED 96.0f